import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { initializeApp } from 'firebase/app'
import { getDatabase , ref, child, get } from "firebase/database"
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'


const Major: NextPage<any> = ({dataDict, dataArray, dataKey}) => {
    const router = useRouter();
    
    useEffect(() => {
        if (dataDict === null) {router.push("/Error")}
    }, [])

    return (
        <>
            <Head>
                <title> {dataKey} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {
                (dataArray === null)? <h1> Null </h1>:
                dataArray.map((object: any) => 
                    <>
                        <div key={object.key}> {object.key} </div>
                        <div key={`content-${object.key}`}> {object.value.courseName} </div>
                    </>
                )
            }
        </>
    )
}

export default Major

export async function getServerSideProps(context: any) {

    const firebaseConfig = {
        apiKey: "AIzaSyD-sgjpJ5oJr1lbD7oxlgPdZbQxESPWXdw",
        authDomain: "buinfoshare.firebaseapp.com",
        databaseURL: "https://buinfoshare-default-rtdb.firebaseio.com/",
        projectId: "buinfoshare",
        storageBucket: "buinfoshare.appspot.com",
    }

    const app = initializeApp(firebaseConfig)
    const database = getDatabase(app);
    
    let data: any = null

    await get(child(ref(database), '/major/' + context.params.Major + '/courses/')).then((snapshot) => {
        data = snapshot.val();
    }).catch((error) => {
        console.log(error)
    })

    let tmpArray: any = []
    for (const property in data) {
        let tmpObj = {
            key: property,
            value: data[property]
        }
        tmpArray.push(tmpObj)
    }

    return {
        props: {
            dataDict: data,
            dataArray: tmpArray,
            dataKey: context.params.Major
        }
    }
}