import type { NextPage } from 'next'
import Navbar from '../../components/navbar/navbar'
import Head from 'next/head'

const Error: NextPage = () => {
  return (
      <>
        <Head>
            <title> Error </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <div>
            Hello
        </div>
      </>
  )
}

export default Error