import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Splash.module.scss'
import Navbar from '../components/navbar/navbar'
import brick from '../public/brick.png'
import Link from 'next/link'
import React, { useEffect } from 'react';
import { useRouter } from 'next/router'

const Home: NextPage = () => {
  const router = useRouter();

  useEffect(() => {
    // Testing purpose turn this on 
    // localStorage.clear()

    if (localStorage.getItem("user") !== null) 
      router.push("/HomePage")
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title> InfoShare </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <main className={styles.splashPage}>
        <div>
          <h2> Welcome To </h2>
          <div>
            <h1> InfoShare </h1>
            <div>
              <Image src={brick} style={{"display": "inline"}} height={150}/>
            </div>
          </div>
          <h3> Thanks for visiting our site. If you are confused about your homework, and wanted to find help. You are at the right place. </h3>
          <Link href={"/Log-in"}>
            <button> Let the Magic Begin </button>
          </Link>
        </div>
      </main>
    </div>
  )
}

export default React.memo(Home)
