import type { NextPage } from 'next'
import Image from 'next/image'
import Navbar from '../../components/navbar/navbar'
import Head from 'next/head'
import brick from '../../public/brick.png'
import styles from '../../styles/LogIn.module.scss'
import { useRouter } from 'next/router'
import Link from 'next/link'

const Login: NextPage = () => {
  const router = useRouter()

  return (
      <>
        <Head>
            <title> Login </title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>

        <main className={styles.loginPage}>
          <section>
            <div>
              <Image src={brick}/>
              <h1> Login </h1>
              <h2> Sign In and start exploring courses</h2>
            </div>
            <div>
              <input type="text" placeholder={"Login"} name="email"/>
              <input type="password" placeholder={"Password"} name="password"/>
              <div> 
                <div>
                  <Link href={"/SignUp"}>
                    <p> Don't have an account </p>
                  </Link>
                </div>
                {/* Do Nothing for now; since there isn't anything for this part */}
                <div>
                  <p> Forget your password? </p>
                </div>
              </div>
            </div>
            <button onClick={() => router.push('/HomePage')}>
              Login
            </button>
          </section>
        </main>
      </>
  )
}

export default Login
